### ISSUE TITLE
Redesign the alternate UI for the cool name list.

### ISSUE THREAD

**Issue by mohitkyadav** [mohitkyadav/cool-name-api#15]
Currently the app shows cool names that are submitted in the app in a long big page wide list and it also covers full page width. An alternate UI is required.

**Comment by CruiseDevice** [comment]
What are your ideas for the improvement in the UI?

**Comment by mohitkyadav** [comment]
It should be more user friendly, currently it's just a list. One approach can be to arrange different types of cool names in different divs, it also is just an idea. I'm bad at UX. 😅

**Comment by CruiseDevice** [comment]
Can be done no problem.

**Comment by mohitkyadav** [comment]
Refer to #29
