### ISSUE TITLE
`/names` leaks other users data and is not safe for concurrent access

### ISSUE THREAD

**Issue by Kissaki** [mohitkyadav/cool-name-api#17]
If I understand correctly, looking at [client.js#L10](https://github.com/mohitkyadav/cool-name-api/blob/master/public/client.js#L10), the `/names` endpoint is used to get the users request result,

However, `/names` returns a simple in memory store that does not take into account multiple users and requests. 

https://github.com/mohitkyadav/cool-name-api/blob/master/server.js#L21-L27

Most importantly this means that you see other users requests and results.

Secondly, this means it is not necessarily safe for concurrent access. It may send the request, another user sends a request, and then you receive your reply - but not for your request but for that of the other user.

**Comment by Kissaki** [comment]
This is not limited to accessing `/names` btw. If you just open the webpage it will use that endpoint so simply opening the webpage triggers that.

**Comment by jeyemwey** [comment]
I will work on that.
