### ISSUE TITLE
Clarification on intent of authors in README

### ISSUE THREAD

**Issue by Kissaki** [mohitkyadav/cool-name-api#23]
The LICENSE file lists authors as per MIT as the copyright holders/authors.

The README currently lists author names in addition to that, and again as copyright holders in the LICENSE block.

Please clarify the intentions regarding this. Should all contributors add themselves to the LICENSE and two places in the README? That seems like a lot of useless duplication effort to me.

I would suggest removing the authors from the license section. That's what the LICENSE file is for. Furthermore either the license badge is deemed sufficient, then there is IMO no use in a headline and it should be at the top or somewhere general, or the MIT license and a link to the LICENSE file should be visible in written text as well.

What is the intention of the authors section in the README?

**Comment by Kissaki** [comment]
See discussion in PR https://github.com/mohitkyadav/cool-name-api/pull/24/files/010d296b9820f320a7cc150db85451ffa9d92dea#r222315318

**Comment by mohitkyadav** [comment]
I think adding contributors to README is a good call. What are your views, @Kissaki ?

> I would suggest removing the authors from the license section.

Sounds great to me. In readme the contributors are more visible. No one reads LICENSE at least I don't.

**Comment by Kissaki** [comment]
> > I would suggest removing the authors from the license section.
> 
> Sounds great to me. In readme the contributors are more visible. No one reads LICENSE at least I don't.

I did not mean the LICENSE file. I meant the license section in the README.

In the current readme, I would remove the license section and move the license shield icon to the general project information, before section, at the end. The license is not the first thing you want to learn about the project, but something you will want to know after reading what the project is about. So that's a good place. Add a short paragraph "this project is licensed under MIT".

Or maybe, actually, personally I would probably just remove the license information from the README file. If viewed on github the license is visible in the project infos anyway. No need for an icon.

When reading in text form one can always just refer to the LICENSE file.

So if you want to keep the info in the README file I would suggest removing the section and adding a short paragraph to the end of the project intro/summary. If you don't, remove it entirely from the README file. We have a LICENSE file anyway and everyone knows to look there by convention.

**Comment by Kissaki** [comment]
As for contributors when I read readmes I am only interested in the project, not the people. If you think about it, when is anyone ever interested in finding out about them, and when is going through the contributors list not an option then.

But I understand the desire to promote oneself in an effort of publicity, making discoverability low barrier of entry - a simple click away.

So yeah, I'd be fine with a contributors section and list in the README. But then some thought should be put into when you would be willing and when you want to add people there. Is one contribution enough? Even a typo fix? Does it have to be a considerable contribution?
