### ISSUE TITLE
Clarify "contribution" on Glitch in README

### ISSUE THREAD

**Issue by Kissaki** [mohitkyadav/cool-name-api#25]
The README currently states:

> Hosted on Glitch, contribute on Glitch.

Given that this projects code is hosted here on GitHub, how are contributions made on Glitch supposed to flow back here?

Isn't editing the a copy on Glitch more of a fork and remixing than actually contributing?

**Comment by mohitkyadav** [comment]
@Kissaki this project is currently hosted on glitch but not public for remixing, and the code is available on github.

**Comment by Kissaki** [comment]
Hm? When I open the link I can press remix this, edit it, and open it just fine. Under a different name of course.

So from what I understand the term remixing is indeed correct. Contributing would be wrong as there is no way for remixes on glitch to directly flow back into this upstream project.

So the text adjustments to the paragraph I made in the README is correct and more fitting. No need for further adjustment.

If you agree then feel free to close this.

**Comment by mohitkyadav** [comment]
@Kissaki I guess I forgot I made this public. Thanks a lot for this conversation and contribution to this repository.
