### ISSUE TITLE
Add a feature to uncoolify the cool names generated

### ISSUE THREAD

**Issue by aashutoshrathi** [mohitkyadav/cool-name-api#27]
Sometimes the cool names are more difficult to understand than Klingon, please make a feature to uncoolify stuff.

**Comment by johncoleman83** [comment]
Do you want this feature to take input of cool names such as: `🔱♓🅰🌴_🌴♓🎗_🎏⛎🌜🎋` and uncoolify the input?  Or as described "uncoolify the coold names generated".  The way described seems to refer to simply giving the user back their original input.  I see them as different tasks.

**Comment by aashutoshrathi** [comment]
I want to take inputs like `🔱♓🅰🌴_🌴♓🎗_🎏⛎🌜🎋`

**Comment by johncoleman83** [comment]
5ur3_n0_pr06_m4k35_53n53.

**Comment by johncoleman83** [comment]
Thanks for letting me contribute. I really like your app.  I had a use case for this one time, and it would have been really cool at the time to have had known about your open API endpoint.

**Comment by mohitkyadav** [comment]
I'm glad to hear that you liked my brainchild, thanks for adding the feature.
I'll ensure that you are mentioned in Changelog of this repo.

**Comment by johncoleman83** [comment]
Thanks!
