### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by PiyushPawar17** [mohitkyadav/cool-name-api#32]
@mohitkyadav Unable to fetch requests from React App.
![capture](https://user-images.githubusercontent.com/25110253/51408473-d2eea900-1b84-11e9-868c-6bbbcc217bc0.PNG)

Please add CORS.

**Comment by PiyushPawar17** [comment]
@mohitkyadav not working.
 Try adding these line below line [15](https://github.com/mohitkyadav/cool-name-api/blob/master/server.js#L15).

```js
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});
```

**Comment by mohitkyadav** [comment]
thanks @PiyushPawar17
